### PR TITLE
[feature] newly added search exponential search

### PR DESCRIPTION
**Pull request by yvrakesh**

### CODE REVIEW

**Comment by ashwek** [comment]
@Yacha-Venkata-Rakesh 

for input,
size = 4
array = 77, 78, 79, 80
search element = 80
your program outputs **Search Not Found**

for input,
Size = 5
Array = 64, 65, 66, 67, 68
search element = 67
your program is stuck somewhere in an **infinite loop** & never exits

When a value is found in an array, prints its index also.

**Comment by kvedala** [comment]
@Yacha-Venkata-Rakesh any update on this ?

**Comment by Yacha-Venkata-Rakesh** [comment]
So sorry for delay I haven't noticed this. I'll try to fix the error by an hour. Thank you for letting me know about the bug.

**Comment by Yacha-Venkata-Rakesh** [comment]
I have updated the code. I hope there are no errors in it. Thanks @ashwek for describing the bug.
Thanks @kvedala reminding me about the issue.
Please let me know in case of any issues regarding code
Thank you.

**Comment by kvedala** [comment]
Thank you @Yacha-Venkata-Rakesh 
Please note that the repo standards have been standardized, improved and automated. After every push to pull-request, a thorough check will inform you of any concerns.
After your latest push,
1. LGTM has commented on the errors it has noticed
2. the auto-checks have also reported errors. You can view them by clicking on the "details" link next to the error. [here is the link for convenience](https://github.com/TheAlgorithms/C/pull/470/checks?check_run_id=901183012) and you can search for "error" to scroll to the error messages.

Please ensure that the CI tests pass without errors and that LGTM does not report any alerts. These concerns must be addressed before the PR can be merged. 
Also, the documentation of the file is not to the standards. Please refer to other files in the repo [like this one](https://github.com/TheAlgorithms/C/blob/master/searching/binary_search.c) and update the code with respect to:
1. documentation following [doxygen protocol](http://doxygen.nl/manual/docblocks.html)
2. add self-test function and confirm the execution using `assert` function

**Pull request closed without merging**
