### PR TITLE
Create stackUsingLinkedList.c

### PR DESCRIPTION
**Pull request by mateuseap**

### CODE REVIEW

**Comment by ashwek** [comment]
@mateuseap ``main`` function isn't doing anything.

**Comment by mateuseap** [comment]
> @mateuseap `main` function isn't doing anything.

Alright. I removed the main function from my code.

**Comment by mateuseap** [comment]
As well, I removed my brazilian portuguese comments from the code too.

**Comment by ashwek** [comment]
@mateuseap thank you for contributing, but we already have an implementation of stack using linked list. Closing PR.

**Pull request closed without merging**
