### PR TITLE
chore: update CMake version #1271

### PR DESCRIPTION
**Pull request by rbevin777**
#### Description of Change
This change is an update to use the latest version of CMake.

#### References
https://github.com/TheAlgorithms/C/issues/1271

#### Checklist

- [x] Added description of change
- [ ] ~~Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)~~
- [ ] ~~Added tests and example, test must pass~~
- [ ] ~~Relevant documentation/comments is changed or added~~
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] ~~Search previous suggestions before making a new one, as yours may be a duplicate.~~
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Review by alexpantyukhin — APPROVED** [review]

**Review by madhavgaba — COMMENTED** [review]
Is 3.22 newer than 3.6? Am i missing something?

**Comment by rbevin777** [comment]
> Is 3.22 newer than 3.6? Am i missing something?

Yea they are using semantic versioning as far as I'm aware

**Review by madhavgaba — APPROVED** [review]

**Comment by rbevin777** [comment]
Is there anything more I need to do with this PR or do i just wait for reviews and approvals?

**Review by Panquesito7 — APPROVED** [review]
Awesome. Thank you! 🚀
Would you like to do the same in the [C++](https://github.com/TheAlgorithms/C-Plus-Plus) repository (https://github.com/TheAlgorithms/C-Plus-Plus/issues/2479)?

**Comment by rbevin777** [comment]
> Awesome. Thank you! 🚀 Would you like to do the same in the [C++](https://github.com/TheAlgorithms/C-Plus-Plus) repository ([TheAlgorithms/C-Plus-Plus#2479](https://github.com/TheAlgorithms/C-Plus-Plus/issues/2479))?

Yea can do

**Pull request merged**
