### PR TITLE
change sol1.c deteted ./a.out and also added sol4.c

### PR DESCRIPTION
**Pull request by AafilUmar**

### CODE REVIEW

**Comment by ashwek** [comment]
@AafilUmar please remove the  executable files _(a.out)_

**Comment by ashwek** [comment]
@AafilUmar please dont add executable files _(a.out)_. These files are generated on compiling the code and are not needed.

**Comment by AafilUmar** [comment]
Yaahh it removed

**Comment by ashwek** [comment]
there is 1 _a.out_ file

**Comment by AafilUmar** [comment]
I modified and deleted now its not there

**Comment by ashwek** [comment]
@AafilUmar the *Files changed* section is showing 3 files:
* __conversions/a.out__
* project_euler/Problem 01/sol1.c
* project_euler/Problem 01/sol4.c 

anyways, i will merge the request, but please dont add executable files to the merge request

**Pull request merged**
