### PR TITLE
fix: file names modified for better readability

### PR DESCRIPTION
**Pull request by meenal2000**
#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/770"></a>

### CODE REVIEW

**Review by meenal2000 — COMMENTED** [review]
the changes are ready to get merged . Whoaa!!

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Please enable [GitHub Actions](https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions) in your repository of this fork in this link: https://github.com/meenal2000/C/actions so that the `DIRECTORY.md` file is updated.

**Comment by meenal2000** [comment]
Hey TheAlgorithms/C , I have modified it . Will you be able to merge now ?
Do tell if you encounter any issues.

**Comment by Panquesito7** [comment]
Good work. Now, to trigger the GitHub Actions, make a small commit (e.g. change a file's name and then change it back how it was).
If GitHub Actions is enabled, we'll see a commit by GitHub Actions updating `DIRECTORY.md`. 🙂

**Review by Panquesito7 — APPROVED** [review]
LGTM. Thank you for your contribution! 🎉 👍

**Comment by meenal2000** [comment]
The pleasure is all mine !

**Pull request merged**
