### PR TITLE
Adding Queue data structure library

### PR DESCRIPTION
**Pull request by shubhamdp**
This is a library for Queue data structure.

### CODE REVIEW

**Comment by shubhamdp** [comment]
@kvedala any plans to review this PR

**Comment by kvedala** [comment]
There has been much changes to the repo. 
Please do the following before review:
1. rebase your branch to the repo master - this will check if all the repo-checks pass
2. the new repo uses CMake auto-build. No need to provide with a custom makefile and no changes need to be made to the 
3. the comments and readme are very nice 👍 please include them as doxygen documentation within the code. You can refer to [this file](https://github.com/TheAlgorithms/C/blob/master/machine_learning/kohonen_som_trace.c). This auto-generates the documentation website [like this](https://thealgorithms.github.io/C/d0/d46/kohonen__som__trace_8c.html)
4. please consolidate the functions into one C file as shown in the reference above and include test cases in the same
Thank you for you contribution and keep 'em coming 😄

**Comment by kvedala** [comment]
please reset back to the original commit. Since your contribution was consolidated to only 1 commit, the rebase should have been much easier without conflicts. 
You can try to use cherry-pick if that is easier.

**Comment by shubhamdp** [comment]
I will close this PR and create a new PR, that would be simple :-)

**Comment by shubhamdp** [comment]
Hey I did the changes as per the doxygen format but still doxygen CI fails on my fork

**Comment by kvedala** [comment]
> Hey I did the changes as per the doxygen format but still doxygen CI fails on my fork.
> Check this commit ([shubhamdp@3e8d9cc](https://github.com/shubhamdp/C/commit/3e8d9ccf303112659468fcd4fce5d33051df0e5c))

1. the CI that is failing is for doxygen - probably because there is no `gh-pages` branch? But This can be ignored.
2. Create the pull-request so it becomes clearer

**Comment by kvedala** [comment]
Reopened in #563

**Pull request closed without merging**
