### PR TITLE
[enhancement] Client_server folder code updated for windows OS as well. 

### LINKED ISSUE #572: client_server don't support windows

### PR DESCRIPTION
**Pull request by kvedala**
#### Description of Change

Existing implementations used BSD sockets and would not compile using MSVC. Code is now updated to use Winsock on windows and BSD sockets on *nix platforms.

#### References

Closes #572 

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/577"></a>

### CODE REVIEW

**Comment by StepfenShawn** [comment]
👍👍 @kvedala

**Comment by kvedala** [comment]
> 👍👍 @kvedala

Feel free to review the changes and suggest nothing missing.

**Comment by kvedala** [comment]
> 👍👍 @kvedala

@StepfenShawn Have you tested the code?

**Comment by StepfenShawn** [comment]
I tested this code and everything works well under Windows. Thank you for your contribution!

**Pull request merged**
