### PR TITLE
LeetCode : Added Solution and modified Readme.md for problem 98

### PR DESCRIPTION
**Pull request by DhruvPasricha**
LeetCode : Added Solution and modified Readme.md for problem 98

- [x] Added description of change
- [x] Added file name matches 
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

### CODE REVIEW

**Comment by DhruvPasricha** [comment]
I am not able to contribute.Can somebody help me ?

**Comment by Panquesito7** [comment]
What is the problem you're experiencing?

**Comment by DhruvPasricha** [comment]
I am having some trouble during the workflow execution.

LeetCode _ Added Solution and modified Readme md for problem 98 by DhruvPasricha · Pull Request #803 · TheAlgorithms_C - Google Chrome 18-02-2021 11_50_55

**Comment by Panquesito7** [comment]
Go check the [`clang-tidy`](https://github.com/TheAlgorithms/C/runs/1919016576) checks directly. That will show you the errors in your code. 🙂

**Pull request closed without merging**
