### PR TITLE
add leetcode n-th Tribonacci number

### PR DESCRIPTION
**Pull request by alexpantyukhin**
#### Description of Change

Add a guide for new LeetCode solutions.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Comment by alexpantyukhin** [comment]
Now I see that the `Directory.md`  has been updated automatically by the workflow.

**Review by Panquesito7 — DISMISSED** [review]
Thanks! 🚀

**Review by StepfenShawn — APPROVED** [review]

**Review by tjgurwara99 — APPROVED** [review]
You might need to resolve conflicts - the directory generator might create some issues like this 😅

It might be best to create a PR after updating `DIRECTORY.md` from master rather than individual PR's updating the directory file. What do you think @Panquesito7?

**Comment by alexpantyukhin** [comment]
Yes, sure!) Sorry for that

**Review by tjgurwara99 — APPROVED** [review]

**Review by StepfenShawn — APPROVED** [review]

**Comment by Panquesito7** [comment]
> It might be best to create a PR after updating `DIRECTORY.md` from master rather than individual PR's updating the directory file. What do you think @Panquesito7?

Like, updating the directory only on the `master` branch?
P.S.: I'll work soon on a few scripts/workflows improvements here and on the C++ repository.

**Review by Panquesito7 — APPROVED** [review]

**Pull request merged**
