### PR TITLE
[feat/fix]: Add contributing guidelines and update templates

### PR DESCRIPTION
**Pull request by Panquesito7**
#### Description of Change

- Add contributing guidelines (similar to [`C-Plus-Plus/CONTRIBUTING.md`](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md)).
- Use the correct links in PR/issue templates.

#### References

#609

#### Checklist

- [x] Added description of change
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/610"></a>

### CODE REVIEW

**Review by cclauss — APPROVED** [review]

**Comment by kvedala** [comment]
Good work 👍

**Review by kvedala — APPROVED** [review]

**Review by ayaankhan98 — APPROVED** [review]
Great!

**Comment by kvedala** [comment]
Please update the README file as well.

**Comment by Panquesito7** [comment]
> Please update the README file as well.

Done.

**Comment by kvedala** [comment]
Please note that the file CONTRIBUTING.md should be in the root folder and not in the `.github` folder.

**Comment by Panquesito7** [comment]
> Please note that the file CONTRIBUTING.md should be in the root folder and not in the `.github` folder.

Done, moved to root directory. 🙂

**Review by kvedala — APPROVED** [review]
👍

**Pull request merged**
