### PR TITLE
Create Kruskal

### PR DESCRIPTION
**Pull request by ishanisamanta**
#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/864"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Hey there! Thank you for submitting a PR! 😄 Sadly, this does not meet our requirements. Check out our [repository standards](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md). Please read them **carefully** and **follow them**. **Let us know if you need any help here or in our [Discord server](https://discord.gg/c7MnfGFGa6).

**Comment by ishanisamanta** [comment]
Hey, please remove the spam/invalid label as I'll be disqualified otherwise from hacktoberfest. I can delete the pull request or make the required changes as soon as possible. Your help will be highly appreciated. Thank you so much.

**Comment by Panquesito7** [comment]
> Hey, please remove the spam/invalid label as I'll be disqualified otherwise from hacktoberfest. I can delete the pull request or make the required changes as soon as possible. Your help will be highly appreciated. Thank you so much.

Please make the necessary changes and I'll remove the label. Currently, it's an invalid PR.

**Comment by ishanisamanta** [comment]
Hey, can you check once now ?

**Comment by Panquesito7** [comment]
> Hey, can you check once now ?

I don't see any updates.

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Still not up to the [**repository standards**](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md). Please update properly.
Let us know if you need any help here or in our [**Discord server**](https://discord.gg/c7MnfGFGa6). 🙂

**Comment by ishanisamanta** [comment]
Hey, what else do I have to change ? Could you please help me out ?

**Comment by Panquesito7** [comment]
> Hey, what else do I have to change ? Could you please help me out ?

Please read our [**repository standards**](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md) and try to update your files according to the [**typical structure of a program**](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#typical-structure-of-a-program).

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Still not up to the [**repository standards**](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md).

**Comment by ishanisamanta** [comment]
Where exactly is the problem ?

**Comment by ishanisamanta** [comment]
All my checks have successfully passed. Please remove the label now.

**Comment by Panquesito7** [comment]
> All my checks have successfully passed. Please remove the label now.

That's because your file should have `.cpp` at the end. Currently, it has no format.
Also, in Hacktoberfest it's not only about making a PR and getting a free T-shirt. These are educational repositories, and you must adhere to our guidelines. It is not about making it quick and fast. 🙂

**Comment by ishanisamanta** [comment]
Hey, is it okay now ?

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
The format of the file is good now, but the code is still not up to the [**repository standards**](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md).

**Comment by ishanisamanta** [comment]
What else do i need to modify ? I did everything according to the repository standards.

**Comment by Panquesito7** [comment]
> What else do i need to modify ? I did everything according to the repository standards.

Your code is missing proper documentation.

**Review by ishanisamanta — COMMENTED** [review]
Please check now, I provided as much documentation as I can.

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Your algorithm/file is still missing proper documentation.
Check the [**repository standards**](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md) for how to make it properly. 🙂

**Pull request closed without merging**
