### PR TITLE
heapsort implementation started at index 1

### PR DESCRIPTION
**Pull request by ericcurtin**
It is wasteful of the first element of the array, so start at 0.
Add swap implementation.

### CODE REVIEW

**Comment by ericcurtin** [comment]
Almost identical to this PR:

https://github.com/TheAlgorithms/C-Plus-Plus/pull/700

**Comment by ericcurtin** [comment]
Fixed merge conflict HeapSort.c -> Heap_Sort.c

**Comment by ericcurtin** [comment]
@danghai you seem to be familiar with this, would you like to review?

**Comment by kvedala** [comment]
@ericcurtin can you please resolve the merge conflicts and test the code. Thanks.

**Pull request closed without merging**
