### PR TITLE
feat : articulation point algorithm

### PR DESCRIPTION
**Pull request by guyroznb**
#### Description of Change
1) adding the articulation point algorithm. A vertex in an undirected connected graph is an articulation point (or cut vertex) iff removing it (and edges through it) disconnects the graph.
2) changing the graph.c and graph.h files by moving the GraphRep structure to the header file.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/645"></a>

### CODE REVIEW

**Comment by guyroznb** [comment]
adding articulation point algorithm

**Comment by kvedala** [comment]
review the contribution guidelines. No reviews will be done until the code is updated per the repo standards
image

**Comment by guyroznb** [comment]
hi, I added description to the script and change the title

**Comment by kvedala** [comment]
unnecessary files changed. Only make changes to your concerned files. Do not make any changes to existing code unless intentional.
image

**Pull request closed without merging**
