### PR TITLE
feat: Project Euler Problem 59 

### PR DESCRIPTION
**Pull request by yashasvi-goel**
#### Checklist

- [x]  Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [x] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/649"></a>

### CODE REVIEW

**Comment by yashasvi-goel** [comment]
@maintainers do I need to take some action about the lgtm-bot?

**Comment by kvedala** [comment]
> @maintainers do I need to take some action about the lgtm-bot?

Yes
1. update the code per the repo [guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#typical-structure-of-a-program)
2. all the checklist items in the description above must be reviewed - which includes reported errors and CI checks.

You can review existing code https://github.com/TheAlgorithms/C/blob/master/project_euler/problem_5/sol3.c
Good code 👍

**Comment by yashasvi-goel** [comment]
updated

**Comment by kvedala** [comment]
As mentioned in the comment above, please
1. update your code per the guidelines
2. fix the alert reported by LGTM.

**Pull request closed without merging**
