### PR TITLE
Create demonetization.c

### PR DESCRIPTION
**Pull request by ashusrma**
Problem involving no. of ways to dispense different currency notes for a particular amount by an ATM machine; involves recursion.

### CODE REVIEW

**Comment by christianbender** [comment]
@ashusrma  Can you give test data?

**Comment by christianbender** [comment]
@ashusrma  Please give test data? And create a simple user interface, not blinking cursor!

**Comment by anujms1999** [comment]
please have a look at #127 pull request .You have merged #128 but code in in #127 . so Please merge that too

**Comment by christianbender** [comment]
@ashusrma I added a simple UI.

**Comment by ashusrma** [comment]
As can be seen from the code, the input will be given in four lines:

First line contains an integer *n *denoting the number of different
denominations available in the currency system.
Second line contains *n* space-separated integers denoting the
denominations in increasing order.
Next line contains *t* denoting the number of test cases.
Next line contains *t* integers, each representing the amount entered in
the ATM.

Sample test cases:

3
2 3 5
1
10

(answer)
4

2
1 2
3
4
10
100

(answer)
3
6
51

**Pull request merged**
