### PR TITLE
Added perfect numbers in a range algorithm

### PR DESCRIPTION
**Pull request by m607stars**
#### Checklist

- [X] Added description of the change
- [X] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [X] Added tests and example, test must pass
- [X] Relevant documentation/comments is changed or added
- [X] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [X] Search previous suggestions before making a new one, as yours may be a duplicate.
- [X] I acknowledge that all my contributions will be made under the project's license.

Notes: All done   

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/638"></a>

### CODE REVIEW

**Comment by kvedala** [comment]
Thank you for your contribution.
Please update the code with the standards elucidated in [contributing guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md)

**Comment by m607stars** [comment]
Can you please tell what exactly do I have to update? In my opinion everything looks fine.

**Comment by kvedala** [comment]
> Can you please tell what exactly do I have to update? In my opinion everything looks fine.

1. click on the suggested link in my previous comment -> for your convenience: https://github.com/TheAlgorithms/C/pull/638#issuecomment-702706593
2. read the file
3. while reading, you will come to a section that describes how the code should be
4. update your code to that specs
5. make a commit
6. push the changes
7. open this pull-request
8. you will see the description box above with a checklist. 
9. do not simply check the boxes. Make sure you have reviewed the links and that all checks are satisfied. 
10. Then, the code can be considered up to the repo standards and the team will review this pull-request.

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Code is not up to the [repository standards](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md).
Please read them **carefully** and **follow them**.

**Pull request closed without merging**
