### PR TITLE
Greedy Strategy problems are added

### PR DESCRIPTION
**Pull request by nikhithabhupal2000**
As mentioned in the issue #37 , I added a folder for Greedy strategy paradigm and implemented two algorithms , 1.Fractional Knapsack and 2.Optimal merge patterns .

### CODE REVIEW

**Comment by AnupKumarPanwar** [comment]
Please don't push the binaries.

**Comment by nikhithabhupal2000** [comment]
@AnupKumarPanwar   Sure I will do it

**Comment by danghai** [comment]
You can add the binary file in .gitignore

**Comment by nikhithabhupal2000** [comment]
I deleted the binaries . Can you check now?

**Comment by nikhithabhupal2000** [comment]
Can someone check the algos and merge the request?

**Comment by kvedala** [comment]
@nikhithabhupal2000 These are good contributions 👍 Can you update the codes to the repo standards:
1. all filenames should be in small-caps with no spaces.
2. a folder `greedy_approach` already exists. However, currently it is not included in CI checks and build automation. But you can still add your code to that folder
3. Please try to rebase your contribution from the upstream master branch for better integration
4. All code is being documented to auto-generate a convenient detailed [website](https://thealgorithms.github.io/C). Please update your code like [this file](https://github.com/TheAlgorithms/C/blob/master/numerical_methods/realtime_stats.c) and other following the [doxygen](https://www.doxygen.nl/manual/docblocks.html) protocol.

Thank you

**Comment by nikhithabhupal2000** [comment]
Okay @kvedala I will do it.
Thanks

**Pull request closed without merging**
