### PR TITLE
Create linkedlist.c

### PR DESCRIPTION
**Pull request by mateuseap**

### CODE REVIEW

**Comment by ashwek** [comment]
@mateuseap ``main`` function isn't doing anything.

**Comment by mateuseap** [comment]
> @mateuseap `main` function isn't doing anything.

For sure, now I removed the main function.

**Comment by mateuseap** [comment]
> @mateuseap `main` function isn't doing anything.

Alright. I removed the main function from my code.

**Comment by ashwek** [comment]
@mateuseap thank you for contributing, but we already have an implementation of linked list. It would be great if you could add features to the already existing program. Closing PR.

**Pull request closed without merging**
