### PR TITLE
fix: hexadecimal_to_octal.c

### PR DESCRIPTION
**Pull request by HarshitVashisht11**
#### Description of Change
Fix to Issue #1330 
I've made the following changes:

-  Removed the newline character from the input string.

-  Improved the binary to octal conversion loop.

-   Added a return statement after printing an error message for invalid hexadecimal input.

#### Checklist

- [x] Added description of change
- [x] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Comment by sk-jiyad** [comment]
Is it running?

**Comment by HarshitVashisht11** [comment]
Yes it is running

**Comment by sk-jiyad** [comment]
No, it's not

**Comment by HarshitVashisht11** [comment]
It's working, can you specify the problem

**Pull request closed without merging**
