### PR TITLE
added solution to Leetcode problem 771.Jewels and Stones

### PR DESCRIPTION
**Pull request by harshraj22**
Added solution to Leetcode problem 771. Jewels and Stones in reference to issue #249

### CODE REVIEW

**Comment by harshraj22** [comment]
Added solution to Leetcode problem 771. Jewels and Stones in reference to issue #249

**Comment by danghai** [comment]
Hi, could you specify it in README?

**Comment by harshraj22** [comment]
Sure @danghai , updated.

**Comment by danghai** [comment]
Thanks. Merge

**Pull request merged**
