### PR TITLE
Added leetcode problem 198

### PR DESCRIPTION
**Pull request by shoniavika**
#### Checklist

- [x ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/571"></a>

### CODE REVIEW

**Comment by shoniavika** [comment]
Hi, I want to add multiple problems to leetcode directory. First I tried adding all three (I'm adding 3) simultaneously,  but Code Formatter fails. Is there any way around it?

**Comment by kvedala** [comment]
Hi Thank you for your contributions.

The existing `leetcode` folder is quite old and hence you will notice that the folder does not conform to the standards of the rest of the repo in terms of:
1. no documentations in the files - the repo is meant for educational purposes so that people can read and learn from the code. 
2. code does not generate an executable because of lack of `main()` function.
3. codes do not implement self-tests to verify the execution is correct for various test cases

We can create a **temporary** work-around but that would make this folder an odd-one out and difficult to support and maintain. The correct way to go about this would be to update the existing folder with respect to the above mentioned points and we would need help on it. This could also be a great opportunity to learn from the code  while documenting them and making them execute. Would you be able to join in on the efforts? Thanks

**Comment by shoniavika** [comment]
Sure, no problem! Just to be clear, the goal is to update leetcode directory, so each file contains 3 aspects you mentioned above?

**Comment by kvedala** [comment]
> Sure, no problem! Just to be clear, the goal is to update leetcode directory, so each file contains 3 aspects you mentioned above?

Yes, please refer to other files in the repo [like this one](https://github.com/TheAlgorithms/C/blob/master/numerical_methods/durand_kerner_roots.c) and [this one](https://github.com/TheAlgorithms/C/blob/master/numerical_methods/qr_eigen_values.c) that have good documentation and self-tests.

**Pull request closed without merging**
