### PR TITLE
Project Euler Solution for Problem 09

### PR DESCRIPTION
**Pull request by Gokcekuler**
Added solution for Problem 09

### CODE REVIEW

**Comment by ashwek** [comment]
@Gokcekuler please format code properly.

**Comment by Gokcekuler** [comment]
@ashwek I added new format.

**Review by hemanth-kotagiri — CHANGES_REQUESTED** [review]
Hello @Gokcekuler. The indentation of your code is ugly. Please maintain the indentation standards specified and commit the new changes to this PR.

**Review by Panquesito7 — COMMENTED** [review]
You may want to check the [repository standards](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md) for better code and documentation. Alternatively, see the [typical structure](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#typical-structure-of-a-program) of a program. 🙂

**Pull request closed without merging**
