### PR TITLE
Created merge_two_sorted_linkedlist.c file in C/data_structures/linked_list/

### PR DESCRIPTION
**Pull request by Deepthi2001**
#### Checklist

- [ ] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [ ] Relevant documentation/comments is changed or added
- [ ] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [ ] Search previous suggestions before making a new one, as yours may be a duplicate.
- [ ] I acknowledge that all my contributions will be made under the project's license.

Notes: 

<a href="https://gitpod.io/#https://github.com/TheAlgorithms/C/pull/668"></a>

### CODE REVIEW

**Review by Panquesito7 — CHANGES_REQUESTED** [review]
Code is not up to the [repository standards](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md).
Please read them **carefully** and **follow them**.

**Comment by Deepthi2001** [comment]
@Panquesito7 I have made the required changes please do check and inform issues if any. thankyou!

**Comment by Deepthi2001** [comment]
@Panquesito7 please do check and update your review. thankyou!

**Comment by Panquesito7** [comment]
> check and update your review

Code is not up to the [standards](https://github.com/TheAlgorithms/C/blob/master/CONTRIBUTING.md) yet.

**Pull request closed without merging**
