### PR TITLE
[docs] add documentation group

### PR DESCRIPTION
**Pull request by kvedala**
#### Description of Change

added `sorting` group in documentation

#### Checklist

- [x] Added description of change
- [ ] Added file name matches [File name guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#New-File-Name-guidelines)
- [ ] Added tests and example, test must pass
- [x] Relevant documentation/comments is changed or added
- [x] PR title follows semantic [commit guidelines](https://github.com/TheAlgorithms/C-Plus-Plus/blob/master/CONTRIBUTING.md#Commit-Guidelines)
- [x] Search previous suggestions before making a new one, as yours may be a duplicate.
- [x] I acknowledge that all my contributions will be made under the project's license.

Notes:

### CODE REVIEW

**Comment by kvedala** [comment]
@tjgurwara99
wanna take a look?

**Comment by tjgurwara99** [comment]
> @tjgurwara99
> wanna take a look?

I don't have my laptop with me right now, can't check on gitpod but it all seems okay

**Comment by ayaankhan98** [comment]
@kvedala please check line 66 to 68 in bead_sort.c

**Comment by ayaankhan98** [comment]
line 75 shell_sort2.cpp memory allocated is never freed

**Comment by kvedala** [comment]
> @kvedala please check line 66 to 68 in bead_sort.c

Using this loop, the author wants to get the next occurrence of '0' in the array every `max` number of steps

**Comment by kvedala** [comment]
> line 75 shell_sort2.cpp memory allocated is never freed

excellent catch. fixed.

**Comment by ayaankhan98** [comment]
> > @kvedala please check line 66 to 68 in bead_sort.c
> 
> Using this loop, the author wants to get the next occurrence of '0' in the array every `max` number of steps

that's fine i was pointing that line terminator (semicolon) of line 67, we can put it at the last of line 66.

**Comment by kvedala** [comment]
> > > @kvedala please check line 66 to 68 in bead_sort.c
> > 
> > 
> > Using this loop, the author wants to get the next occurrence of '0' in the array every `max` number of steps
> 
> that's fine i was pointing that line terminator (semicolon) of line 67, we can put it at the last of line 66.

Remember that the formatting is taken care of by the `clang-formatter` automatically as per the specs. 
Try to make the fix you suggested on gitpod. Does it not get reverted back? :)

**Comment by ayaankhan98** [comment]
> > > > @kvedala please check line 66 to 68 in bead_sort.c
> > > 
> > > 
> > > Using this loop, the author wants to get the next occurrence of '0' in the array every `max` number of steps
> > 
> > 
> > that's fine i was pointing that line terminator (semicolon) of line 67, we can put it at the last of line 66.
> 
> Remember that the formatting is taken care of by the `clang-formatter` automatically as per the specs.
> Try to make the fix you suggested on gitpod. Does it not get reverted back? :)

yeah it get reverted back :)

**Pull request merged**
